# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.3.0
_src_path: https://github.com/mbercx/python-copier
description: Package for the MC3D-source pipeline.
package_name: mc3d-source
