# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.10.1
_src_path: https://github.com/mbercx/python-copier
description: Package for the MC3D-source pipeline.
doc_deploy: github
docs: mkdocs
package_name: mc3d-source
