max_concurrent: 1000
max_structure_size: 10
parent_group: structure/source
relax_group: workchain/test/relaxbigcells
pw_code: sirius-pw@daint-mc

overrides:
  clean_workdir: False
  base_relax:
    pw: &pw
      parameters:
         DIRECT_MINIMIZATION:
           nlcg_maxiter: 500
      parallelization:
        npool: 9
      settings:
        cmdline:
          - -sirius_cfg
          - sirius.json
      metadata:
        options: &optionsi
          prepend_text: "echo '{}' | jq '.control = {verbosity: 1}' > sirius.json"
          account: mr32
          queue_name: normal
          resources:
            num_cores_per_mpiproc: 2
            num_machines: 2
          max_wallclock_seconds: 84000
  base_init_relax:
    pw: *pw
